-- TODO : 상품 시퀀스 DROP 및 CREATE
-- 상품 ID 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_GOODS;
CREATE SEQUENCE SQ_GOODS
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

-- TODO : 상품 테이블 DROP

DROP TABLE TB_GOODS CASCADE CONSTRAINTS;

-- TODO : 상품 테이블 CREATE
CREATE TABLE TB_GOODS
(
    GOODS_ID        NUMBER NOT NULL PRIMARY KEY,
    CATEGORY     VARCHAR2(1000),
    SELLER_ID       VARCHAR2(1000),
    SELLING_AREA_ID VARCHAR2(1000),
    TITLE           VARCHAR2(100),
    STATUS          VARCHAR(30) DEFAULT '판매중',
    SELL_PRICE      NUMBER,
    VIEW_COUNT      NUMBER DEFAULT 0,
    DESCRIPTION     VARCHAR2(500),
    REFRESHED_TIME  TIMESTAMP,
    ORIGIN_PRICE NUMBER,
    TAG VARCHAR2(1000),
    IMAGE_URL VARCHAR2(1000),
    DELETE_YN       VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME     VARCHAR2(255),
    UPDATE_TIME     VARCHAR2(255),
    DELETE_TIME     VARCHAR2(255)
);





-- -- TODO : 유저 시퀀스
-- -- 상품 ID 번호 부여 시퀀스 1부터 시작
-- DROP SEQUENCE SQ_USER;
-- CREATE SEQUENCE SQ_USER
--     INCREMENT BY 1 START WITH 1
--     MINVALUE 1
--     MAXVALUE 99999999;
--
-- -- TODO : 유저 테이블 DROP
-- DROP TABLE TB_USER CASCADE CONSTRAINTS;
--
-- -- TODO : 유저 테이블 CREATE
-- CREATE TABLE TB_USER
-- (
--     USER_NUM      NUMBER NOT NULL PRIMARY KEY,
--     USER_ID       VARCHAR2(20),
--     USER_PASSWORD      VARCHAR2(1000),
--     USER_NAME     VARCHAR2(1000),
--     NICK          VARCHAR2(1000),
--     MOBILE_NUMBER VARCHAR(11),
--     EMAIL         VARCHAR2(1000),
--     RATING_SCORE  VARCHAR2(1000),
--     CREATE_AT     TIMESTAMP,
--     SIDO_AREA_ID  NUMBER(4),
--     SIGG_AREA_ID  NUMBER(4),
--     EMD_AREA_ID   NUMBER(4),
--     ROLE          VARCHAR2(100),
--     ACTIVATED     CHAR(1),
--     DELETE_YN     VARCHAR2(1) DEFAULT 'N',
--     INSERT_TIME   VARCHAR2(255),
--     UPDATE_TIME   VARCHAR2(255),
--     DELETE_TIME   VARCHAR2(255)
-- );


-- TODO : 유저 시퀀스
-- 상품 ID 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_USER;
CREATE SEQUENCE SQ_USER
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

DROP SEQUENCE SQ_ROLE;
CREATE SEQUENCE SQ_ROLE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

-- TODO : 유저 테이블 DROP
DROP TABLE TB_USER CASCADE CONSTRAINTS;
DROP TABLE TB_ROLE CASCADE CONSTRAINTS;
DROP TABLE TB_USER_ROLE CASCADE CONSTRAINTS;

-- TODO : 유저 테이블 CREATE
CREATE TABLE TB_USER
(
    ID NUMBER NOT NULL PRIMARY KEY,
    EMAIL VARCHAR2(1000) UNIQUE,
    PASSWORD VARCHAR2(1000),
    USERNAME VARCHAR2(1000),
    ADDRESS VARCHAR2(1000),
    MOBILE_NUMBER VARCHAR2(30),
    NICK VARCHAR2(1000),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);
CREATE TABLE TB_ROLE(
                        ID NUMBER NOT NULL PRIMARY KEY,
                        NAME VARCHAR2(1000) UNIQUE
);

CREATE TABLE TB_USER_ROLE (
                              USER_ID NUMBER NOT NULL,
                              ROLE_ID NUMBER NOT NULL,
                              PRIMARY KEY (USER_ID, ROLE_ID)
);



-- TODO : 알림 시퀀스 DROP 및 CREATE
-- 상품 ID 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_NOTIFICATIONS;
CREATE SEQUENCE SQ_NOTIFICATIONS
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

-- TODO : 알림 테이블 DROP
DROP TABLE TB_NOTIFICATIONS CASCADE CONSTRAINTS;

-- TODO : 알림 테이블 CREATE
CREATE TABLE TB_NOTIFICATIONS
(
    NOTIFICATION_ID NUMBER NOT NULL PRIMARY KEY,
    RECEIVER_ID     NUMBER,
    MESSAGE         VARCHAR2(255),
    READ_OR_NOT     CHAR(1),
    TYPE            VARCHAR2(100),
    REFERENCE_ID    NUMBER,
    CREATED_AT      TIMESTAMP,
    DELETE_YN       VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME     VARCHAR2(255),
    UPDATE_TIME     VARCHAR2(255),
    DELETE_TIME     VARCHAR2(255)
);



-- TODO : 찜 시퀀스 DROP 및 CREATE
-- 상품 ID 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_WISHLISTS;
CREATE SEQUENCE SQ_WISHLISTS
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

-- TODO : 찜 테이블 DROP
DROP TABLE TB_WISHLISTS CASCADE CONSTRAINTS;

-- TODO : 찜 테이블 CREATE
CREATE TABLE TB_WISHLISTS
(
    WISH_LIST_ID NUMBER NOT NULL PRIMARY KEY,
    GOODS_ID     NUMBER,
    REGISTER_ID  NUMBER,
    CREATED_AT   TIMESTAMP,
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);



-- TODO : 채팅 시퀀스 DROP 및 CREATE
-- 상품 ID 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_CHATMESSAGES;
CREATE SEQUENCE SQ_CHATMESSAGES
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

-- TODO : 채팅 테이블 DROP
DROP TABLE TB_CHATMESSAGES CASCADE CONSTRAINTS;

-- TODO : 채팅 테이블 CREATE
CREATE TABLE TB_CHATMESSAGES
(
    CHAT_MESSAGES_ID NUMBER NOT NULL PRIMARY KEY,
    CHAT_ROOM_ID     NUMBER,
    SENDER_ID        NUMBER,
    READ_OR_NOT      CHAR(1),
    CREATED_AT       TIMESTAMP,
    DELETE_YN        VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME      VARCHAR2(255),
    UPDATE_TIME      VARCHAR2(255),
    DELETE_TIME      VARCHAR2(255)
);


-- TODO : 채팅방 시퀀스 DROP 및 CREATE
-- 상품 ID 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_CHATROOM;
CREATE SEQUENCE SQ_CHATROOM
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

-- TODO : 채팅방 테이블 DROP
DROP TABLE TB_CHATROOM CASCADE CONSTRAINTS;

-- TODO : 채팅방 테이블 CREATE
CREATE TABLE TB_CHATROOM
(
    CHAT_ROOM_ID NUMBER NOT NULL PRIMARY KEY,
    BUYER_ID     NUMBER,
    GOODS_ID     NUMBER,
    CREATED_AT   TIMESTAMP,
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);



-- TODO : 알림키워드 시퀀스 DROP 및 CREATE
-- 상품 ID 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_NOTIFICATIONSKEYWORDS;
CREATE SEQUENCE SQ_NOTIFICATIONSKEYWORDS
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

-- TODO : 알림키워드 채팅방 테이블 DROP
DROP TABLE TB_NOTIFICATIONSKEYWORDS CASCADE CONSTRAINTS;

-- TODO : 알림키워드 테이블 CREATE
CREATE TABLE TB_NOTIFICATIONSKEYWORDS
(
    NOTIFICATIONS_KEYWORDS_ID NUMBER NOT NULL PRIMARY KEY,
    REGISTER_ID               NUMBER,
    KEYWORD                   VARCHAR(10),
    READ_OR_NOT               CHAR(1),
    CREATED_AT                TIMESTAMP,
    DELETE_YN                 VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME               VARCHAR2(255),
    UPDATE_TIME               VARCHAR2(255),
    DELETE_TIME               VARCHAR2(255)
);


-- TODO : 상품 이미지 시퀀스 DROP 및 CREATE
DROP SEQUENCE SQ_CATEGORY;
CREATE SEQUENCE SQ_CATEGORY START WITH 1 INCREMENT BY 1;

-- TODO : 상품 이미지 테이블 DROP 및 CREATE
DROP TABLE TB_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE TB_CATEGORY
(
    CATEGORY_ID          NUMBER NOT NULL PRIMARY KEY,
    CATEGORY_NAME   VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

DROP SEQUENCE SQ_AREAS;
CREATE SEQUENCE SQ_AREAS START WITH 1 INCREMENT BY 1;

-- TODO : 상품 이미지 테이블 DROP 및 CREATE
DROP TABLE TB_AREAS CASCADE CONSTRAINTS;

CREATE TABLE TB_AREAS
(
    AREA_ID          NUMBER NOT NULL PRIMARY KEY,
    AREA_NAME   VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);


DROP SEQUENCE SQ_FILE;
CREATE SEQUENCE SQ_FILE START WITH 1 INCREMENT BY 1;

-- TODO : 상품 이미지 테이블 DROP 및 CREATE
DROP TABLE TB_FILE CASCADE CONSTRAINTS;

-- Upload Table
CREATE TABLE TB_FILE
(
    FID          NUMBER NOT NULL PRIMARY KEY,
    FILE_NAME    VARCHAR2(1000),
    FILE_TYPE    VARCHAR2(1000),
    FILE_DATA    BLOB,
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- TODO : 자유게시판 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_FB;
CREATE SEQUENCE SQ_FB
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 자유게시판 테이블 DROP
DROP TABLE TB_FB CASCADE CONSTRAINTS;
-- TODO : 자유게시판 테이블 CREATE
CREATE TABLE TB_FB
(
    FNO      	    NUMBER NOT NULL PRIMARY KEY,
    NICK	        VARCHAR2(1000),
    FB_TITLE	    VARCHAR2(1000),
    FB_CONTENT      VARCHAR2(4000),
    FB_CNT	        NUMBER DEFAULT '0',
    FB_CATEGORY	    VARCHAR2(1000),
    FB_RCNT   	    NUMBER DEFAULT '0',
    FB_LIKE    	    NUMBER DEFAULT '0',
    FB_TAG   	    VARCHAR2(1000) NULL,
    FILE_NAME       VARCHAR2(1000) ,
    BLOB_FILE       BLOB,
    DELETE_YN  	    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME	    VARCHAR2(255),
    UPDATE_TIME 	VARCHAR2(255),
    DELETE_TIME 	VARCHAR2(255)
);


-- -- TODO : 자유게시판 카테고리 테이블 CREATE
DROP TABLE TB_FB_CATEGORY CASCADE CONSTRAINT;
--------------------------------------------------------
--  DDL for Table TB_FB_CATEGORY
-------------------------------------------------------
CREATE TABLE TB_FB_CATEGORY (
                                FB_CID VARCHAR2(50) NOT NULL PRIMARY KEY,
                                FB_CTITLE VARCHAR2(1000),
                                DELETE_YN CHAR(1) DEFAULT 'N',
                                INSERT_TIME VARCHAR2(1000) ,
                                UPDATE_TIME VARCHAR2(1000),
                                DELETE_TIME VARCHAR2(1000)
);

-- TODO : 추천게시판 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_BB;
CREATE SEQUENCE SQ_BB
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 추천게시판 테이블 DROP
DROP TABLE TB_BB CASCADE CONSTRAINTS;
-- TODO : 추천게시판 테이블 CREATE
CREATE TABLE TB_BB
(
    BNO      	    NUMBER NOT NULL PRIMARY KEY,
    NICK	        VARCHAR2(1000),
    BB_TITLE	    VARCHAR2(1000),
    BB_CONTENT      VARCHAR2(4000),
    BB_CNT	        NUMBER DEFAULT '0',
    BB_CATEGORY	    VARCHAR2(1000),
    BB_RCNT   	    NUMBER DEFAULT '0',
    BB_LIKE    	    NUMBER DEFAULT '0',
    BB_TAG   	    VARCHAR2(1000),
    FILE_NAME       VARCHAR2(1000) ,
    BLOB_FILE       BLOB,
    DELETE_YN  	    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME	    VARCHAR2(255),
    UPDATE_TIME 	VARCHAR2(255),
    DELETE_TIME 	VARCHAR2(255)
);

-- -- TODO : 추천게시판 카테고리 테이블 CREATE
DROP TABLE TB_BB_CATEGORY CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_BB_CATEGORY (
                                BB_CID VARCHAR2(50) NOT NULL PRIMARY KEY,
                                BB_CTITLE VARCHAR2(1000),
                                DELETE_YN CHAR(1) DEFAULT 'N',
                                INSERT_TIME VARCHAR2(1000) ,
                                UPDATE_TIME VARCHAR2(1000),
                                DELETE_TIME VARCHAR2(1000)
);

-- TODO : 모임게시판 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_MB;
CREATE SEQUENCE SQ_MB
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 모임게시판 테이블 DROP
DROP TABLE TB_MB CASCADE CONSTRAINTS;
-- TODO : 모임게시판 테이블 CREATE
CREATE TABLE TB_MB
(
    MNO      	    NUMBER NOT NULL PRIMARY KEY,
    NICK	        VARCHAR2(1000),
    MB_TITLE	    VARCHAR2(1000),
    MB_CONTENT      VARCHAR2(4000),
    MB_CNT	        NUMBER DEFAULT '0',
    MB_CATEGORY	    VARCHAR2(1000),
    MB_RCNT   	    NUMBER DEFAULT '0',
    MB_LIKE    	    NUMBER DEFAULT '0',
    MB_TAG   	    VARCHAR2(1000),
    FILE_NAME       VARCHAR2(1000) ,
    BLOB_FILE       BLOB,
    DELETE_YN  	    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME	    VARCHAR2(255),
    UPDATE_TIME 	VARCHAR2(255),
    DELETE_TIME 	VARCHAR2(255)
);

-- -- TODO : 모임게시판 카테고리 테이블 CREATE
DROP TABLE TB_MB_CATEGORY CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_MB_CATEGORY (
                                MB_CID VARCHAR2(50) NOT NULL PRIMARY KEY,
                                MB_CTITLE VARCHAR2(1000),
                                DELETE_YN CHAR(1) DEFAULT 'N',
                                INSERT_TIME VARCHAR2(1000) ,
                                UPDATE_TIME VARCHAR2(1000),
                                DELETE_TIME VARCHAR2(1000)
);


-- TODO : 분실게시판 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_LB;
CREATE SEQUENCE SQ_LB
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 분실게시판 테이블 DROP
DROP TABLE TB_LB CASCADE CONSTRAINTS;
-- TODO : 분실게시판 테이블 CREATE
CREATE TABLE TB_LB
(
    LNO      	    NUMBER NOT NULL PRIMARY KEY,
    NICK	        VARCHAR2(1000),
    LB_TITLE	    VARCHAR2(1000),
    LB_CONTENT      VARCHAR2(4000),
    LB_CNT	        NUMBER DEFAULT '0',
    LB_CATEGORY	    VARCHAR2(1000),
    LB_RCNT   	    NUMBER DEFAULT '0',
    LB_LIKE    	    NUMBER DEFAULT '0',
    LB_TAG   	    VARCHAR2(1000),
    FILE_NAME       VARCHAR2(1000) ,
    BLOB_FILE       BLOB,
    DELETE_YN  	    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME	    VARCHAR2(255),
    UPDATE_TIME 	VARCHAR2(255),
    DELETE_TIME 	VARCHAR2(255)
);

-- -- TODO : 분실게시판 카테고리 테이블 CREATE
DROP TABLE TB_LB_CATEGORY CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_LB_CATEGORY (
                                LB_CID VARCHAR2(50) NOT NULL PRIMARY KEY,
                                LB_CTITLE VARCHAR2(1000),
                                DELETE_YN CHAR(1) DEFAULT 'N',
                                INSERT_TIME VARCHAR2(1000) ,
                                UPDATE_TIME VARCHAR2(1000),
                                DELETE_TIME VARCHAR2(1000)
);
-- TODO : 다이어리 시퀀스 DROP 및 CREATE
DROP SEQUENCE SQ_DIARY;
CREATE SEQUENCE SQ_DIARY START WITH 1 INCREMENT BY 1;

-- TODO : 다이어리 테이블 DROP 및 CREATE
DROP TABLE TB_DIARY CASCADE CONSTRAINTS;

CREATE TABLE TB_DIARY
(
    DNO         NUMBER NOT NULL PRIMARY KEY,
    USER_ID     NUMBER,
    D_TITLE     VARCHAR2(1000),
    D_CONTENT   VARCHAR2(1000),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

DROP SEQUENCE SQ_FREE_BOARD_REPLY;
CREATE SEQUENCE SQ_FREE_BOARD_REPLY START WITH 1 INCREMENT BY 1;

DROP TABLE TB_FREE_BOARD_REPLY CASCADE CONSTRAINTS ;

CREATE TABLE TB_FREE_BOARD_REPLY
(
    FRNO NUMBER NOT NULL PRIMARY KEY,
    FNO NUMBER,
    NICK VARCHAR2(1000),
    FB_REPLY VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

DROP SEQUENCE SQ_GOOD_COMMENT;
CREATE SEQUENCE SQ_GOOD_COMMENT START WITH 1 INCREMENT BY 1;

DROP TABLE TB_GOOD_COMMENT CASCADE CONSTRAINTS ;

CREATE TABLE TB_GOOD_COMMENT
(
    COMMENT_ID NUMBER NOT NULL PRIMARY KEY,
    GOODS_ID NUMBER,
    NICK VARCHAR2(1000),
    COMM VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

DROP SEQUENCE SQ_GOOD_REPLY;
CREATE SEQUENCE SQ_GOOD_REPLY START WITH 1 INCREMENT BY 1;

DROP TABLE TB_GOOD_REPLY CASCADE CONSTRAINTS ;

CREATE TABLE TB_GOOD_REPLY
(
    REPLY_ID NUMBER NOT NULL PRIMARY KEY,
    GOODS_ID NUMBER,
    COMMENT_ID NUMBER,
    NICK VARCHAR2(1000),
    REPLY VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- TODO : TODO 시퀀스 DROP 및 CREATE
DROP SEQUENCE SQ_TODO;
CREATE SEQUENCE SQ_TODO START WITH 1 INCREMENT BY 1;

-- TODO : TODO 테이블 DROP 및 CREATE
DROP TABLE TB_TODO CASCADE CONSTRAINTS;

CREATE TABLE TB_TODO
(
    TNO         NUMBER NOT NULL PRIMARY KEY,
    USER_ID     NUMBER,
    T_CONTENT   VARCHAR2(1000),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

-- TODO : 자유게시판 좋아요 시퀀스 DROP 및 CREATE
DROP SEQUENCE SQ_FB_LIKE;
CREATE SEQUENCE SQ_FB_LIKE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- -- TODO : 자유게시판 좋아요 테이블 CREATE
DROP TABLE TB_FB_LIKE CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_FB_LIKE (
                            FB_LIKE_ID  NUMBER NOT NULL PRIMARY KEY,
                            FNO         NUMBER,
                            USER_ID     NUMBER

);

-- TODO : 추천게시판 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_BB;
CREATE SEQUENCE SQ_BB
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 추천게시판 테이블 DROP
DROP TABLE TB_BB CASCADE CONSTRAINTS;
-- TODO : 추천게시판 테이블 CREATE
CREATE TABLE TB_BB
(
    BNO      	    NUMBER NOT NULL PRIMARY KEY,
    NICK	        VARCHAR2(1000),
    BB_TITLE	    VARCHAR2(1000),
    BB_CONTENT      VARCHAR2(4000),
    BB_CNT	        NUMBER DEFAULT '0',
    BB_CATEGORY	    VARCHAR2(1000),
    BB_RCNT   	    NUMBER DEFAULT '0',
    BB_LIKE    	    NUMBER DEFAULT '0',
    BB_TAG   	    VARCHAR2(1000),
    FILE_NAME       VARCHAR2(1000) ,
    BLOB_FILE       BLOB,
    DELETE_YN  	    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME	    VARCHAR2(255),
    UPDATE_TIME 	VARCHAR2(255),
    DELETE_TIME 	VARCHAR2(255)
);

-- -- TODO : 추천게시판 카테고리 테이블 CREATE
DROP TABLE TB_BB_CATEGORY CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_BB_CATEGORY (
                                BB_CID VARCHAR2(50) NOT NULL PRIMARY KEY,
                                BB_CTITLE VARCHAR2(1000),
                                DELETE_YN CHAR(1) DEFAULT 'N',
                                INSERT_TIME VARCHAR2(1000) ,
                                UPDATE_TIME VARCHAR2(1000),
                                DELETE_TIME VARCHAR2(1000)
);

-- TODO : 모임게시판 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_MB;
CREATE SEQUENCE SQ_MB
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 모임게시판 테이블 DROP
DROP TABLE TB_MB CASCADE CONSTRAINTS;
-- TODO : 모임게시판 테이블 CREATE
CREATE TABLE TB_MB
(
    MNO      	    NUMBER NOT NULL PRIMARY KEY,
    NICK	        VARCHAR2(1000),
    MB_TITLE	    VARCHAR2(1000),
    MB_CONTENT      VARCHAR2(4000),
    MB_CNT	        NUMBER DEFAULT '0',
    MB_CATEGORY	    VARCHAR2(1000),
    MB_RCNT   	    NUMBER DEFAULT '0',
    MB_LIKE    	    NUMBER DEFAULT '0',
    MB_TAG   	    VARCHAR2(1000),
    FILE_NAME       VARCHAR2(1000) ,
    BLOB_FILE       BLOB,
    DELETE_YN  	    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME	    VARCHAR2(255),
    UPDATE_TIME 	VARCHAR2(255),
    DELETE_TIME 	VARCHAR2(255)
);

-- -- TODO : 모임게시판 카테고리 테이블 CREATE
DROP TABLE TB_MB_CATEGORY CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_MB_CATEGORY (
                                MB_CID VARCHAR2(50) NOT NULL PRIMARY KEY,
                                MB_CTITLE VARCHAR2(1000),
                                DELETE_YN CHAR(1) DEFAULT 'N',
                                INSERT_TIME VARCHAR2(1000) ,
                                UPDATE_TIME VARCHAR2(1000),
                                DELETE_TIME VARCHAR2(1000)
);


-- TODO : 분실게시판 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_LB;
CREATE SEQUENCE SQ_LB
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 분실게시판 테이블 DROP
DROP TABLE TB_LB CASCADE CONSTRAINTS;
-- TODO : 분실게시판 테이블 CREATE
CREATE TABLE TB_LB
(
    LNO      	    NUMBER NOT NULL PRIMARY KEY,
    NICK	        VARCHAR2(1000),
    LB_TITLE	    VARCHAR2(1000),
    LB_CONTENT      VARCHAR2(4000),
    LB_CNT	        NUMBER DEFAULT '0',
    LB_CATEGORY	    VARCHAR2(1000),
    LB_RCNT   	    NUMBER DEFAULT '0',
    LB_LIKE    	    NUMBER DEFAULT '0',
    LB_TAG   	    VARCHAR2(1000),
    FILE_NAME       VARCHAR2(1000) ,
    BLOB_FILE       BLOB,
    DELETE_YN  	    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME	    VARCHAR2(255),
    UPDATE_TIME 	VARCHAR2(255),
    DELETE_TIME 	VARCHAR2(255)
);

-- -- TODO : 분실게시판 카테고리 테이블 CREATE
DROP TABLE TB_LB_CATEGORY CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_LB_CATEGORY (
                                LB_CID VARCHAR2(50) NOT NULL PRIMARY KEY,
                                LB_CTITLE VARCHAR2(1000),
                                DELETE_YN CHAR(1) DEFAULT 'N',
                                INSERT_TIME VARCHAR2(1000) ,
                                UPDATE_TIME VARCHAR2(1000),
                                DELETE_TIME VARCHAR2(1000)
);

-- TODO : 상품 찜 시퀀스 DROP 및 CREATE
-- 게시판 목록 번호 부여 시퀀스 1부터 시작
DROP SEQUENCE SQ_GOOD_CART;
CREATE SEQUENCE SQ_GOOD_CART
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- TODO : 분실게시판 테이블 DROP
DROP TABLE TB_GOOD_CART CASCADE CONSTRAINTS;
-- TODO : 분실게시판 테이블 CREATE
CREATE TABLE TB_GOOD_CART
(
    CART_ID      	    NUMBER NOT NULL PRIMARY KEY,
    GOODS_ID	        NUMBER,
    USER_ID	    NUMBER
);


-- -- TODO : 자유게시판 댓글 테이블 CREATE
DROP SEQUENCE SQ_FB_COMMENT;
CREATE SEQUENCE SQ_FB_COMMENT START WITH 1 INCREMENT BY 1;

DROP TABLE TB_FB_COMMENT CASCADE CONSTRAINTS ;

CREATE TABLE TB_FB_COMMENT
(
    COMMENT_ID   NUMBER NOT NULL PRIMARY KEY,
    FNO          NUMBER,
    NICK         VARCHAR2(1000),
    COMM         VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- -- TODO : 자유게시판 대댓글 테이블 CREATE
DROP SEQUENCE SQ_FB_REPLY;
CREATE SEQUENCE SQ_FB_REPLY START WITH 1 INCREMENT BY 1;

DROP TABLE TB_FB_REPLY CASCADE CONSTRAINTS ;

CREATE TABLE TB_FB_REPLY
(
    REPLY_ID NUMBER NOT NULL PRIMARY KEY,
    FNO NUMBER,
    COMMENT_ID NUMBER,
    NICK VARCHAR2(1000),
    REPLY VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- -- TODO : 추천게시판 댓글 테이블 CREATE
DROP SEQUENCE SQ_BB_COMMENT;
CREATE SEQUENCE SQ_BB_COMMENT START WITH 1 INCREMENT BY 1;

DROP TABLE TB_BB_COMMENT CASCADE CONSTRAINTS ;

CREATE TABLE TB_BB_COMMENT
(
    COMMENT_ID   NUMBER NOT NULL PRIMARY KEY,
    BNO          NUMBER,
    NICK         VARCHAR2(1000),
    COMM         VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- -- TODO : 추천게시판 대댓글 테이블 CREATE
DROP SEQUENCE SQ_BB_REPLY;
CREATE SEQUENCE SQ_BB_REPLY START WITH 1 INCREMENT BY 1;

DROP TABLE TB_BB_REPLY CASCADE CONSTRAINTS ;

CREATE TABLE TB_BB_REPLY
(
    REPLY_ID NUMBER NOT NULL PRIMARY KEY,
    BNO NUMBER,
    COMMENT_ID NUMBER,
    NICK VARCHAR2(1000),
    REPLY VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- -- TODO : 모임게시판 댓글 테이블 CREATE
DROP SEQUENCE SQ_MB_COMMENT;
CREATE SEQUENCE SQ_MB_COMMENT START WITH 1 INCREMENT BY 1;

DROP TABLE TB_MB_COMMENT CASCADE CONSTRAINTS ;

CREATE TABLE TB_MB_COMMENT
(
    COMMENT_ID   NUMBER NOT NULL PRIMARY KEY,
    MNO          NUMBER,
    NICK         VARCHAR2(1000),
    COMM         VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- -- TODO : 모임게시판 대댓글 테이블 CREATE
DROP SEQUENCE SQ_MB_REPLY;
CREATE SEQUENCE SQ_MB_REPLY START WITH 1 INCREMENT BY 1;

DROP TABLE TB_MB_REPLY CASCADE CONSTRAINTS ;

CREATE TABLE TB_MB_REPLY
(
    REPLY_ID NUMBER NOT NULL PRIMARY KEY,
    MNO NUMBER,
    COMMENT_ID NUMBER,
    NICK VARCHAR2(1000),
    REPLY VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- -- TODO : 분실게시판 댓글 테이블 CREATE
DROP SEQUENCE SQ_LB_COMMENT;
CREATE SEQUENCE SQ_LB_COMMENT START WITH 1 INCREMENT BY 1;

DROP TABLE TB_LB_COMMENT CASCADE CONSTRAINTS ;

CREATE TABLE TB_LB_COMMENT
(
    COMMENT_ID   NUMBER NOT NULL PRIMARY KEY,
    LNO          NUMBER,
    NICK         VARCHAR2(1000),
    COMM         VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- -- TODO : 분실게시판 대댓글 테이블 CREATE
DROP SEQUENCE SQ_LB_REPLY;
CREATE SEQUENCE SQ_LB_REPLY START WITH 1 INCREMENT BY 1;

DROP TABLE TB_LB_REPLY CASCADE CONSTRAINTS ;

CREATE TABLE TB_LB_REPLY
(
    REPLY_ID NUMBER NOT NULL PRIMARY KEY,
    LNO NUMBER,
    COMMENT_ID NUMBER,
    NICK VARCHAR2(1000),
    REPLY VARCHAR2(1000),
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- TODO : 추천게시판 좋아요 시퀀스 DROP 및 CREATE
DROP SEQUENCE SQ_BB_LIKE;
CREATE SEQUENCE SQ_BB_LIKE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- -- TODO : 추천게시판 좋아요 테이블 CREATE
DROP TABLE TB_BB_LIKE CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_BB_LIKE (
                            BB_LIKE_ID  NUMBER NOT NULL PRIMARY KEY,
                            BNO         NUMBER,
                            USER_ID     NUMBER
);

-- TODO : 모임게시판 좋아요 시퀀스 DROP 및 CREATE
DROP SEQUENCE SQ_MB_LIKE;
CREATE SEQUENCE SQ_MB_LIKE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- -- TODO : 모임게시판 좋아요 테이블 CREATE
DROP TABLE TB_MB_LIKE CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_MB_LIKE (
                            MB_LIKE_ID  NUMBER NOT NULL PRIMARY KEY,
                            MNO         NUMBER,
                            USER_ID     NUMBER
);

-- TODO : 분실게시판 좋아요 시퀀스 DROP 및 CREATE
DROP SEQUENCE SQ_LB_LIKE;
CREATE SEQUENCE SQ_LB_LIKE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;
-- -- TODO : 분실게시판 좋아요 테이블 CREATE
DROP TABLE TB_LB_LIKE CASCADE CONSTRAINT;
--------------------------------------------------------
CREATE TABLE TB_LB_LIKE (
                            LB_LIKE_ID  NUMBER NOT NULL PRIMARY KEY,
                            LNO         NUMBER,
                            USER_ID     NUMBER
);


DROP SEQUENCE SQ_PROFILE_IMAGE;
CREATE SEQUENCE SQ_PROFILE_IMAGE START WITH 1 INCREMENT BY 1;

-- TODO : 상품 이미지 테이블 DROP 및 CREATE
DROP TABLE TB_PROFILE_IMAGE CASCADE CONSTRAINTS;

-- Upload Table
CREATE TABLE TB_PROFILE_IMAGE
(
    PID          NUMBER NOT NULL PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    FILE_NAME    VARCHAR2(1000),
    FILE_TYPE    VARCHAR2(1000),
    FILE_DATA    BLOB,
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

COMMIT;

